MODEL:
  META_ARCHITECTURE: "ClsNet"
  BACKBONE:
    NAME: "build_mnetv1_backbone"
    FREEZE_AT: 0
  MNET:
    OUT_FEATURES: ['linear']
    WIDTH_MULT: 0.25 # Width multiplier - adjusts number of channels in each layer by this amount
  CLSNET:
    ENABLE: True
    NUM_CLASSES: 17 # assume max 1?
    INPUT_SIZE: 224 # resizes image to 224x224

DATASETS:
  TRAIN: ("imagenet_train", )
  TEST: ("imagenet_val", )
DATALOADER:
  ASPECT_RATIO_GROUPING: False
  NUM_WORKERS: 4
SOLVER:
  IMS_PER_BATCH: 256
  BASE_LR: 0.1
  STEPS: (150000, 180000)
  MAX_ITER: 200000
INPUT:
  CROP:
    ENABLED: False
VERSION: 2
